# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Personal\我的文档\py\test1\form1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(819, 471)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setSizeGripEnabled(True)
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 820, 468))
        self.tabWidget.setMinimumSize(QtCore.QSize(820, 468))
        self.tabWidget.setMaximumSize(QtCore.QSize(820, 468))
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox1 = QtWidgets.QGroupBox(self.tab)
        self.groupBox1.setGeometry(QtCore.QRect(360, 20, 101, 91))
        self.groupBox1.setObjectName("groupBox1")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox1)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox1)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 60, 89, 16))
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(260, 160, 109, 58))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit1_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit1_2.setReadOnly(True)
        self.lineEdit1_2.setObjectName("lineEdit1_2")
        self.gridLayout_3.addWidget(self.lineEdit1_2, 0, 1, 1, 1)
        self.lineEdit2_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit2_2.setReadOnly(True)
        self.lineEdit2_2.setObjectName("lineEdit2_2")
        self.gridLayout_3.addWidget(self.lineEdit2_2, 1, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 160, 75, 51))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setGeometry(QtCore.QRect(470, 230, 331, 201))
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton1.setEnabled(False)
        self.pushButton1.setGeometry(QtCore.QRect(110, 100, 41, 41))
        self.pushButton1.setAutoFillBackground(False)
        self.pushButton1.setStyleSheet("")
        self.pushButton1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Resources/固定铰支.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton1.setIcon(icon)
        self.pushButton1.setIconSize(QtCore.QSize(35, 35))
        self.pushButton1.setCheckable(False)
        self.pushButton1.setDefault(False)
        self.pushButton1.setFlat(False)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton3.setEnabled(False)
        self.pushButton3.setGeometry(QtCore.QRect(110, 25, 41, 41))
        self.pushButton3.setAutoFillBackground(False)
        self.pushButton3.setStyleSheet("")
        self.pushButton3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Resources/左端悬臂ico.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton3.setIcon(icon1)
        self.pushButton3.setIconSize(QtCore.QSize(38, 35))
        self.pushButton3.setCheckable(False)
        self.pushButton3.setChecked(False)
        self.pushButton3.setAutoRepeat(False)
        self.pushButton3.setAutoExclusive(False)
        self.pushButton3.setDefault(False)
        self.pushButton3.setFlat(False)
        self.pushButton3.setObjectName("pushButton3")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton2.setEnabled(False)
        self.pushButton2.setGeometry(QtCore.QRect(190, 100, 41, 41))
        self.pushButton2.setAutoFillBackground(False)
        self.pushButton2.setStyleSheet("")
        self.pushButton2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Resources/活动铰支.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton2.setIcon(icon2)
        self.pushButton2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton2.setCheckable(False)
        self.pushButton2.setDefault(False)
        self.pushButton2.setFlat(False)
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton4.setEnabled(False)
        self.pushButton4.setGeometry(QtCore.QRect(190, 25, 41, 41))
        self.pushButton4.setAutoFillBackground(False)
        self.pushButton4.setStyleSheet("")
        self.pushButton4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Resources/右端悬臂ico.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton4.setIcon(icon3)
        self.pushButton4.setIconSize(QtCore.QSize(38, 35))
        self.pushButton4.setCheckable(False)
        self.pushButton4.setAutoDefault(True)
        self.pushButton4.setDefault(False)
        self.pushButton4.setFlat(False)
        self.pushButton4.setObjectName("pushButton4")
        self.groupBox2 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox2.setGeometry(QtCore.QRect(10, 20, 81, 171))
        self.groupBox2.setTitle("")
        self.groupBox2.setObjectName("groupBox2")
        self.Type3 = QtWidgets.QRadioButton(self.groupBox2)
        self.Type3.setGeometry(QtCore.QRect(10, 150, 89, 16))
        self.Type3.setChecked(False)
        self.Type3.setObjectName("Type3")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.Type3)
        self.Type1 = QtWidgets.QRadioButton(self.groupBox2)
        self.Type1.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.Type1.setChecked(False)
        self.Type1.setObjectName("Type1")
        self.buttonGroup.addButton(self.Type1)
        self.Type2 = QtWidgets.QRadioButton(self.groupBox2)
        self.Type2.setEnabled(False)
        self.Type2.setGeometry(QtCore.QRect(10, 80, 89, 31))
        self.Type2.setCheckable(True)
        self.Type2.setChecked(True)
        self.Type2.setObjectName("Type2")
        self.buttonGroup.addButton(self.Type2)
        self.lineEdit22 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit22.setGeometry(QtCore.QRect(260, 90, 61, 20))
        self.lineEdit22.setInputMask("")
        self.lineEdit22.setFrame(True)
        self.lineEdit22.setDragEnabled(False)
        self.lineEdit22.setObjectName("lineEdit22")
        self.lineEdit23 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit23.setGeometry(QtCore.QRect(260, 130, 61, 20))
        self.lineEdit23.setInputMask("")
        self.lineEdit23.setMaxLength(32767)
        self.lineEdit23.setObjectName("lineEdit23")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(260, 70, 51, 20))
        self.label_5.setObjectName("label_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(263, 110, 61, 20))
        self.label_19.setObjectName("label_19")
        self.lineEdit11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit11.setGeometry(QtCore.QRect(100, 150, 61, 21))
        self.lineEdit11.setStatusTip("")
        self.lineEdit11.setObjectName("lineEdit11")
        self.lineEdit12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit12.setGeometry(QtCore.QRect(180, 150, 61, 21))
        self.lineEdit12.setObjectName("lineEdit12")
        self.checkBox1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox1.setEnabled(False)
        self.checkBox1.setGeometry(QtCore.QRect(124, 70, 16, 16))
        self.checkBox1.setText("")
        self.checkBox1.setCheckable(True)
        self.checkBox1.setChecked(False)
        self.checkBox1.setTristate(False)
        self.checkBox1.setObjectName("checkBox1")
        self.checkBox2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox2.setEnabled(False)
        self.checkBox2.setGeometry(QtCore.QRect(204, 70, 16, 16))
        self.checkBox2.setText("")
        self.checkBox2.setObjectName("checkBox2")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(390, 140, 71, 20))
        self.label_11.setObjectName("label_11")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 251, 211))
        self.frame_2.setStyleSheet("image: url(:/Resources/21.jpg);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(470, 0, 329, 219))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 313, 211))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 10, 0)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit3 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit3.setObjectName("lineEdit3")
        self.gridLayout_2.addWidget(self.lineEdit3, 4, 1, 1, 1)
        self.lineEdit1 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit1.setObjectName("lineEdit1")
        self.gridLayout_2.addWidget(self.lineEdit1, 2, 1, 1, 1)
        self.lineEdit21 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit21.setReadOnly(False)
        self.lineEdit21.setObjectName("lineEdit21")
        self.gridLayout_2.addWidget(self.lineEdit21, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit2 = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit2.setInputMask("")
        self.lineEdit2.setText("")
        self.lineEdit2.setMaxLength(32767)
        self.lineEdit2.setObjectName("lineEdit2")
        self.gridLayout_2.addWidget(self.lineEdit2, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setMaximumSize(QtCore.QSize(300, 15))
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 451, 181))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout11.setSpacing(1)
        self.horizontalLayout11.setObjectName("horizontalLayout11")
        self.tabWidget.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_4.setGeometry(QtCore.QRect(70, 40, 231, 71))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 89, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_6.setGeometry(QtCore.QRect(130, 20, 89, 16))
        self.radioButton_6.setObjectName("radioButton_6")
        self.label31 = QtWidgets.QLabel(self.tab_5)
        self.label31.setGeometry(QtCore.QRect(90, 140, 54, 12))
        self.label31.setObjectName("label31")
        self.comboBox = QtWidgets.QComboBox(self.tab_5)
        self.comboBox.setGeometry(QtCore.QRect(190, 140, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_5.setGeometry(QtCore.QRect(70, 190, 231, 151))
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 91, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 70, 91, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label31_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label31_2.setGeometry(QtCore.QRect(110, 30, 61, 16))
        self.label31_2.setObjectName("label31_2")
        self.label31_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label31_3.setGeometry(QtCore.QRect(110, 70, 51, 16))
        self.label31_3.setObjectName("label31_3")
        self.label31_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label31_4.setGeometry(QtCore.QRect(110, 110, 51, 16))
        self.label31_4.setObjectName("label31_4")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_6.setGeometry(QtCore.QRect(340, 190, 231, 151))
        self.groupBox_6.setObjectName("groupBox_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 30, 91, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 110, 91, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label31_8 = QtWidgets.QLabel(self.groupBox_6)
        self.label31_8.setGeometry(QtCore.QRect(110, 30, 81, 16))
        self.label31_8.setObjectName("label31_8")
        self.label31_10 = QtWidgets.QLabel(self.groupBox_6)
        self.label31_10.setGeometry(QtCore.QRect(110, 110, 51, 16))
        self.label31_10.setObjectName("label31_10")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_7.setGeometry(QtCore.QRect(340, 0, 341, 181))
        self.groupBox_7.setObjectName("groupBox_7")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_7)
        self.textBrowser.setGeometry(QtCore.QRect(20, 20, 301, 151))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(590, 190, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 30, 141, 301))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label = QtWidgets.QLabel(self.groupBox_8)
        self.label.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label.setObjectName("label")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 50, 81, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_12 = QtWidgets.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(100, 50, 54, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_8)
        self.label_13.setGeometry(QtCore.QRect(100, 130, 54, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_8)
        self.label_14.setGeometry(QtCore.QRect(20, 110, 54, 12))
        self.label_14.setObjectName("label_14")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 130, 81, 20))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_15 = QtWidgets.QLabel(self.groupBox_8)
        self.label_15.setGeometry(QtCore.QRect(20, 180, 54, 12))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_8)
        self.label_16.setGeometry(QtCore.QRect(100, 200, 54, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 200, 81, 20))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_17 = QtWidgets.QLabel(self.groupBox_8)
        self.label_17.setGeometry(QtCore.QRect(20, 250, 71, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 270, 81, 20))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.label_18 = QtWidgets.QLabel(self.groupBox_8)
        self.label_18.setGeometry(QtCore.QRect(100, 270, 54, 16))
        self.label_18.setObjectName("label_18")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_9.setGeometry(QtCore.QRect(460, 10, 291, 351))
        self.groupBox_9.setObjectName("groupBox_9")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.groupBox_9)
        self.textBrowser_2.setGeometry(QtCore.QRect(30, 30, 241, 291))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(500, 370, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_3 = QtWidgets.QFrame(self.tab_3)
        self.frame_3.setGeometry(QtCore.QRect(190, 20, 261, 341))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(20, 10, 221, 211))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_2.setGeometry(QtCore.QRect(300, 70, 89, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_7.setGeometry(QtCore.QRect(300, 140, 89, 16))
        self.radioButton_7.setObjectName("radioButton_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(470, 50, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(470, 100, 113, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_6.setGeometry(QtCore.QRect(470, 150, 113, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dialog"))
        self.groupBox1.setTitle(_translate("MainWindow", "计算类型选择"))
        self.radioButton_4.setText(_translate("MainWindow", "数值计算"))
        self.radioButton_5.setText(_translate("MainWindow", "符号计算"))
        self.label_9.setText(_translate("MainWindow", "左"))
        self.label_10.setText(_translate("MainWindow", "右"))
        self.pushButton_2.setText(_translate("MainWindow", "计算"))
        self.groupBox_3.setTitle(_translate("MainWindow", "梁类型选择"))
        self.Type3.setText(_translate("MainWindow", " 综合梁"))
        self.Type1.setText(_translate("MainWindow", " 悬臂梁"))
        self.Type2.setText(_translate("MainWindow", " 外伸梁\n"
"(简支梁)"))
        self.lineEdit22.setText(_translate("MainWindow", "0"))
        self.lineEdit23.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", " 左外伸L1"))
        self.label_19.setText(_translate("MainWindow", "右外伸L2"))
        self.label_11.setText(_translate("MainWindow", " 支座反力"))
        self.groupBox_2.setTitle(_translate("MainWindow", "参数输入"))
        self.label_7.setText(_translate("MainWindow", "    杆长/(mm)"))
        self.lineEdit21.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "   均布载荷 Q"))
        self.label_4.setText(_translate("MainWindow", "   集 中 力 P"))
        self.label_3.setText(_translate("MainWindow", "   集中力偶 M"))
        self.label_6.setText(_translate("MainWindow", "   距左端位置/(mm),力的大小/(N);"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "静定梁分析"))
        self.groupBox_4.setTitle(_translate("MainWindow", "壳体类型"))
        self.radioButton.setText(_translate("MainWindow", "薄壁圆壳"))
        self.radioButton_6.setText(_translate("MainWindow", "球罐"))
        self.label31.setText(_translate("MainWindow", "选择材料"))
        self.comboBox.setItemText(0, _translate("MainWindow", "碳钢"))
        self.groupBox_5.setTitle(_translate("MainWindow", "基本数据"))
        self.label31_2.setText(_translate("MainWindow", "内径(mm)"))
        self.label31_3.setText(_translate("MainWindow", "壁厚(mm)"))
        self.label31_4.setText(_translate("MainWindow", "压力(mm)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "基本数据"))
        self.lineEdit_7.setText(_translate("MainWindow", "196"))
        self.lineEdit_9.setText(_translate("MainWindow", "0.3"))
        self.label31_8.setText(_translate("MainWindow", "弹性模量 GPa"))
        self.label31_10.setText(_translate("MainWindow", "泊松比"))
        self.groupBox_7.setTitle(_translate("MainWindow", "计算结果"))
        self.pushButton.setText(_translate("MainWindow", "计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "薄壳中应力计算"))
        self.groupBox_8.setTitle(_translate("MainWindow", "正应力"))
        self.label.setText(_translate("MainWindow", "x轴方向"))
        self.label_12.setText(_translate("MainWindow", "MPa"))
        self.label_13.setText(_translate("MainWindow", "MPa"))
        self.label_14.setText(_translate("MainWindow", "y轴方向"))
        self.label_15.setText(_translate("MainWindow", "xy轴方向"))
        self.label_16.setText(_translate("MainWindow", "MPa"))
        self.label_17.setText(_translate("MainWindow", "斜面 α 角度"))
        self.label_18.setText(_translate("MainWindow", "°"))
        self.groupBox_9.setTitle(_translate("MainWindow", "计算结果"))
        self.pushButton_4.setText(_translate("MainWindow", "计算"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "应力圆分析"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "截面特性及压杆"))
        self.radioButton_2.setText(_translate("MainWindow", "固定端"))
        self.radioButton_7.setText(_translate("MainWindow", "自由端"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "页"))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

