# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Personal\Desktop\结题\源代码 - 副本\form1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 680)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 450))
        MainWindow.setMaximumSize(QtCore.QSize(65535, 680))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Resources/活动铰支.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setSizeGripEnabled(True)
        self.gridLayout_4 = QtWidgets.QGridLayout(MainWindow)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(MainWindow)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 450))
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 880, 678))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setMinimumSize(QtCore.QSize(700, 650))
        self.tabWidget.setMaximumSize(QtCore.QSize(65535, 65535))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 400))
        self.groupBox_2.setMaximumSize(QtCore.QSize(6666, 400))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox1 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox1.setFlat(True)
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox1)
        self.radioButton_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox1)
        self.radioButton_5.setEnabled(False)
        self.radioButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_5.setChecked(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.horizontalLayout_5.addWidget(self.groupBox1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_3.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setTextFormat(QtCore.Qt.RichText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 1, 0, 1, 1)
        self.textEdit_1 = QtWidgets.QTextEdit(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.textEdit_1.setFont(font)
        self.textEdit_1.setReadOnly(True)
        self.textEdit_1.setObjectName("textEdit_1")
        self.gridLayout_3.addWidget(self.textEdit_1, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 210))
        self.tableWidget.setSizeIncrement(QtCore.QSize(381, 265))
        self.tableWidget.setBaseSize(QtCore.QSize(381, 265))
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(86)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 400))
        self.groupBox.setMaximumSize(QtCore.QSize(6666, 400))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 6, 0, 1, 1)
        self.Kbox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Kbox.sizePolicy().hasHeightForWidth())
        self.Kbox.setSizePolicy(sizePolicy)
        self.Kbox.setMinimumSize(QtCore.QSize(100, 30))
        self.Kbox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.Kbox.setFont(font)
        self.Kbox.setMaximum(1000)
        self.Kbox.setProperty("value", 8)
        self.Kbox.setObjectName("Kbox")
        self.gridLayout_2.addWidget(self.Kbox, 6, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit24 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit24.sizePolicy().hasHeightForWidth())
        self.lineEdit24.setSizePolicy(sizePolicy)
        self.lineEdit24.setMinimumSize(QtCore.QSize(60, 20))
        self.lineEdit24.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit24.setFont(font)
        self.lineEdit24.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit24.setStyleSheet("background-color: rgba(170, 170, 255, 150);")
        self.lineEdit24.setMaxLength(30000)
        self.lineEdit24.setReadOnly(True)
        self.lineEdit24.setObjectName("lineEdit24")
        self.horizontalLayout.addWidget(self.lineEdit24)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 5, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 3, 1, 1)
        self.Nbox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Nbox.sizePolicy().hasHeightForWidth())
        self.Nbox.setSizePolicy(sizePolicy)
        self.Nbox.setMinimumSize(QtCore.QSize(10, 30))
        self.Nbox.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.Nbox.setFont(font)
        self.Nbox.setStyleSheet("background-color: rgba(170, 170, 255, 150);")
        self.Nbox.setReadOnly(True)
        self.Nbox.setProperty("value", 0)
        self.Nbox.setObjectName("Nbox")
        self.gridLayout_2.addWidget(self.Nbox, 6, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_22.setTextFormat(QtCore.Qt.PlainText)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 0, 0, 1, 3)
        self.lineEdit21 = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit21.sizePolicy().hasHeightForWidth())
        self.lineEdit21.setSizePolicy(sizePolicy)
        self.lineEdit21.setMinimumSize(QtCore.QSize(100, 20))
        self.lineEdit21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit21.setFont(font)
        self.lineEdit21.setMaxLength(30000)
        self.lineEdit21.setReadOnly(False)
        self.lineEdit21.setObjectName("lineEdit21")
        self.gridLayout_2.addWidget(self.lineEdit21, 1, 1, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(40, 0))
        self.label_20.setMaximumSize(QtCore.QSize(666, 16777215))
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 6, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 3, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 35))
        self.pushButton_5.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_1)
        self.verticalLayout.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.verticalLayout.addWidget(self.radioButton_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setEnabled(False)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setSizeIncrement(QtCore.QSize(0, 200))
        self.groupBox_3.setMouseTracking(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton1 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton1.setEnabled(False)
        self.pushButton1.setGeometry(QtCore.QRect(100, 110, 41, 41))
        self.pushButton1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton1.setAutoFillBackground(False)
        self.pushButton1.setStyleSheet("")
        self.pushButton1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Resources/固定铰支.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton1.setIcon(icon1)
        self.pushButton1.setIconSize(QtCore.QSize(35, 35))
        self.pushButton1.setCheckable(False)
        self.pushButton1.setDefault(False)
        self.pushButton1.setFlat(False)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton2.setEnabled(False)
        self.pushButton2.setGeometry(QtCore.QRect(170, 110, 41, 41))
        self.pushButton2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton2.setAutoFillBackground(False)
        self.pushButton2.setStyleSheet("")
        self.pushButton2.setText("")
        self.pushButton2.setIcon(icon)
        self.pushButton2.setIconSize(QtCore.QSize(35, 35))
        self.pushButton2.setCheckable(False)
        self.pushButton2.setDefault(False)
        self.pushButton2.setFlat(False)
        self.pushButton2.setObjectName("pushButton2")
        self.lineEdit22 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit22.setGeometry(QtCore.QRect(95, 160, 51, 20))
        self.lineEdit22.setInputMask("")
        self.lineEdit22.setFrame(True)
        self.lineEdit22.setDragEnabled(False)
        self.lineEdit22.setObjectName("lineEdit22")
        self.lineEdit23 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit23.setGeometry(QtCore.QRect(166, 160, 51, 20))
        self.lineEdit23.setInputMask("")
        self.lineEdit23.setMaxLength(32767)
        self.lineEdit23.setObjectName("lineEdit23")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(97, 90, 51, 20))
        self.label_5.setObjectName("label_5")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(165, 90, 61, 20))
        self.label_19.setObjectName("label_19")
        self.lineEdit11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit11.setEnabled(False)
        self.lineEdit11.setGeometry(QtCore.QRect(240, 110, 61, 21))
        self.lineEdit11.setStatusTip("")
        self.lineEdit11.setObjectName("lineEdit11")
        self.lineEdit12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit12.setEnabled(False)
        self.lineEdit12.setGeometry(QtCore.QRect(240, 160, 61, 21))
        self.lineEdit12.setObjectName("lineEdit12")
        self.checkBox1 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox1.setEnabled(False)
        self.checkBox1.setGeometry(QtCore.QRect(100, 20, 91, 51))
        self.checkBox1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox1.setStyleSheet("QCheckBox::indicator {\n"
"\n"
"    width: 20px;\n"
"    height:20px;\n"
"}\n"
"")
        self.checkBox1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Resources/左端悬臂ico.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox1.setIcon(icon2)
        self.checkBox1.setIconSize(QtCore.QSize(45, 45))
        self.checkBox1.setCheckable(True)
        self.checkBox1.setChecked(False)
        self.checkBox1.setTristate(False)
        self.checkBox1.setObjectName("checkBox1")
        self.checkBox2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox2.setEnabled(False)
        self.checkBox2.setGeometry(QtCore.QRect(210, 20, 101, 51))
        self.checkBox2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.checkBox2.setStyleSheet("QCheckBox::indicator {\n"
"\n"
"    width: 20px;\n"
"    height:20px;\n"
"}\n"
"")
        self.checkBox2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Resources/右端悬臂ico.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.checkBox2.setIcon(icon3)
        self.checkBox2.setIconSize(QtCore.QSize(45, 45))
        self.checkBox2.setObjectName("checkBox2")
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setGeometry(QtCore.QRect(90, 70, 221, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Type2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.Type2.setEnabled(False)
        self.Type2.setGeometry(QtCore.QRect(10, 92, 71, 31))
        self.Type2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Type2.setCheckable(True)
        self.Type2.setChecked(True)
        self.Type2.setObjectName("Type2")
        self.Type1 = QtWidgets.QRadioButton(self.groupBox_3)
        self.Type1.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.Type1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Type1.setChecked(False)
        self.Type1.setObjectName("Type1")
        self.Type3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.Type3.setEnabled(False)
        self.Type3.setGeometry(QtCore.QRect(10, 157, 71, 31))
        self.Type3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Type3.setChecked(False)
        self.Type3.setObjectName("Type3")
        self.pushButton1.raise_()
        self.pushButton2.raise_()
        self.lineEdit22.raise_()
        self.lineEdit23.raise_()
        self.label_5.raise_()
        self.label_19.raise_()
        self.lineEdit11.raise_()
        self.lineEdit12.raise_()
        self.checkBox1.raise_()
        self.checkBox2.raise_()
        self.line.raise_()
        self.Type1.raise_()
        self.Type2.raise_()
        self.Type3.raise_()
        self.Type3.raise_()
        self.Type2.raise_()
        self.Type1.raise_()
        self.Type2.raise_()
        self.Type1.raise_()
        self.Type3.raise_()
        self.gridLayout_2.addWidget(self.groupBox_3, 2, 1, 3, 3)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_4.addWidget(self.line_2)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(0, 147, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.groupBox_10)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit21, self.lineEdit22)
        MainWindow.setTabOrder(self.lineEdit22, self.lineEdit23)
        MainWindow.setTabOrder(self.lineEdit23, self.lineEdit)
        MainWindow.setTabOrder(self.lineEdit, self.Kbox)
        MainWindow.setTabOrder(self.Kbox, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.lineEdit12)
        MainWindow.setTabOrder(self.lineEdit12, self.lineEdit24)
        MainWindow.setTabOrder(self.lineEdit24, self.tableWidget)
        MainWindow.setTabOrder(self.tableWidget, self.Nbox)
        MainWindow.setTabOrder(self.Nbox, self.textEdit_1)
        MainWindow.setTabOrder(self.textEdit_1, self.scrollArea)
        MainWindow.setTabOrder(self.scrollArea, self.radioButton_1)
        MainWindow.setTabOrder(self.radioButton_1, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.lineEdit11)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "剪力弯矩计算器"))
        self.groupBox_2.setTitle(_translate("MainWindow", "结果"))
        self.groupBox1.setTitle(_translate("MainWindow", "计算类型选择"))
        self.radioButton_4.setText(_translate("MainWindow", "数值计算"))
        self.radioButton_5.setText(_translate("MainWindow", "符号计算\n"
"(待开发)"))
        self.pushButton_2.setText(_translate("MainWindow", "计算"))
        self.label_11.setText(_translate("MainWindow", "                  支座反力"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TYPE"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "COORD"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "P/T/Q1"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Q2"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "参数信息输入"))
        self.pushButton_6.setText(_translate("MainWindow", "导出>>>"))
        self.label_8.setText(_translate("MainWindow", "杆分段 N"))
        self.label_21.setText(_translate("MainWindow", "杆数据输入"))
        self.label.setText(_translate("MainWindow", "="))
        self.lineEdit24.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "   该色不用填写"))
        self.label_7.setText(_translate("MainWindow", "杆长/(mm)"))
        self.label_22.setText(_translate("MainWindow", "输入格式:   a1,a2,a3...an (下同)               "))
        self.lineEdit21.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "段分段 K"))
        self.pushButton_3.setText(_translate("MainWindow", "<<<导入"))
        self.pushButton_5.setText(_translate("MainWindow", "重新开始&(F5)"))
        self.pushButton_5.setShortcut(_translate("MainWindow", "F5"))
        self.radioButton_1.setText(_translate("MainWindow", "清除表中数据"))
        self.radioButton_2.setText(_translate("MainWindow", "不清除表数据"))
        self.groupBox_3.setTitle(_translate("MainWindow", "梁类型选择"))
        self.lineEdit22.setText(_translate("MainWindow", "0"))
        self.lineEdit23.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "左外伸L1"))
        self.label_19.setText(_translate("MainWindow", "右外伸L2"))
        self.Type2.setText(_translate("MainWindow", " 外伸梁\n"
"(简支梁)"))
        self.Type1.setText(_translate("MainWindow", " 悬臂梁"))
        self.Type3.setText(_translate("MainWindow", " 综合梁\n"
"(待开发)"))
        self.groupBox_10.setTitle(_translate("MainWindow", "画板"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "静定梁分析"))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

